# ===============================
# 1. CONEXIÓN A POSTGRESQL
# ===============================
spring.datasource.url=jdbc:postgresql://localhost:5432/kedo_db
spring.datasource.username=postgres
# SUSTITUYE la siguiente línea con tu contraseña real de PostgreSQL:
spring.datasource.password=IAMtheBesT12!

# ===============================
# 2. CONFIGURACIÓN DE HIBERNATE / JPA
# ===============================
spring.jpa.hibernate.ddl-auto=update
# Le decimos a Hibernate que hable en el "dialecto" exacto de PostgreSQL
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
# Muestra las consultas SQL en la consola (útil para ver qué hace por debajo)
spring.jpa.show-sql=true

# ===============================
# 3. PUERTO DEL SERVIDOR
# ===============================
server.port=8081